# Generated by Django 2.0.2 on 2018-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=40, verbose_name='Student Name')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('stu_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('par_name', models.CharField(max_length=40, verbose_name='Parent Name')),
                ('par_address', models.CharField(max_length=60)),
                ('home_telephone', models.CharField(max_length=40)),
                ('place_employment', models.CharField(blank=True, max_length=50)),
                ('work_telephone', models.CharField(blank=True, max_length=40)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('par_name2', models.CharField(max_length=40, verbose_name='Parent Name')),
                ('par_address2', models.CharField(max_length=60)),
                ('home_telephone2', models.CharField(max_length=40)),
                ('place_employment2', models.CharField(blank=True, max_length=50)),
                ('work_telephone2', models.CharField(blank=True, max_length=40)),
                ('occupation2', models.CharField(blank=True, max_length=50)),
                ('email2', models.EmailField(max_length=254)),
            ],
        ),
    ]
