# Generated by Django 2.0.2 on 2018-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='par_address',
            field=models.CharField(max_length=60, verbose_name='Parent Address'),
        ),
        migrations.AlterField(
            model_name='register',
            name='place_employment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Place of Employment'),
        ),
        migrations.AlterField(
            model_name='register',
            name='stu_address',
            field=models.CharField(max_length=50, verbose_name='Student Address'),
        ),
    ]
